version: "3.8"
services:
  frontend:
    image: rplace-frontend
    ports:
      - "3000:3000"
    networks:
      - webnet
  backend:
    image: rplace-backend
    ports:
      - "80:80"
    networks:
      - webnet
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - webnet
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rplace
      - POSTGRES_PORT=5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webnet
networks:
  webnet:
